-- GENERATED by tools/update-pi-data.py on 2026-10-03. Don't edit by hand: rerun it (mise run pi-data).
-- Expected Power Infusion DPS gain per damage spec, in percent. Base: the mean of Ulria's PI sims
-- (4-piece, hero trees averaged) and bloodmallet's PI chart (2026-09-30 04:05), plus a small, clipped nudge
-- from where the spec ranks in whoshouldgetpi.com's logs (raw log deltas are biased negative, so they
-- never set the value).
-- Specs not listed (tanks, healers, Augmentation) are never ranked as Power Infusion targets.
local _, RaidUtility = ...

RaidUtility.PI_DATA = {
    updated = "2026-10-03",
    gain = {
        [265] = 6.07, -- Affliction Warlock: sheet 5.44, bloodmallet 5.82, logs +0.44
        [62] = 3.38, -- Arcane Mage: sheet 3.04, bloodmallet 3.39, logs +0.16
        [71] = 3.12, -- Arms Warrior: sheet 3.12, bloodmallet 3.19, logs -0.03
        [259] = 6.63, -- Assassination Rogue: sheet 6.34, bloodmallet 5.91, logs +0.50
        [102] = 3.29, -- Balance Druid: sheet 3.21, logs +0.08
        [253] = 3.53, -- Beast Mastery Hunter: sheet 3.58, bloodmallet 3.48
        [266] = 4.59, -- Demonology Warlock: sheet 3.93, bloodmallet 4.25, logs +0.50
        [267] = 2.62, -- Destruction Warlock: sheet 2.55, bloodmallet 2.63, logs +0.03
        [1467] = 3.96, -- Devastation Evoker: sheet 4.04, logs -0.08
        [1480] = 2.56, -- Devourer Demon Hunter: sheet 2.56, bloodmallet 2.55
        [262] = 4.50, -- Elemental Shaman: sheet 3.88, bloodmallet 4.67, logs +0.22
        [263] = 5.19, -- Enhancement Shaman: sheet 4.67, bloodmallet 4.70, logs +0.50
        [103] = 4.34, -- Feral Druid: sheet 4.22, bloodmallet 4.72, logs -0.13
        [63] = 4.30, -- Fire Mage: sheet 4.75, bloodmallet 4.45, logs -0.30
        [251] = 3.56, -- Frost Death Knight: sheet 3.78, bloodmallet 3.35
        [64] = 2.12, -- Frost Mage: sheet 2.71, bloodmallet 2.53, logs -0.50
        [72] = 2.09, -- Fury Warrior: sheet 2.74, bloodmallet 2.44, logs -0.50
        [577] = 2.40, -- Havoc Demon Hunter: sheet 2.71, bloodmallet 2.10 (manual PI timing)
        [254] = 5.08, -- Marksmanship Hunter: sheet 4.53, bloodmallet 4.63, logs +0.50
        [260] = 2.14, -- Outlaw Rogue: sheet 2.65, bloodmallet 2.63 (manual PI timing), logs -0.50
        [70] = 4.93, -- Retribution Paladin: sheet 4.09, bloodmallet 5.05, logs +0.36
        [258] = 2.33, -- Shadow Priest: sheet 2.85, bloodmallet 2.81, logs -0.50
        [261] = 0.88, -- Subtlety Rogue: sheet 1.50, bloodmallet 1.22, logs -0.48
        [255] = 3.32, -- Survival Hunter: sheet 3.62, bloodmallet 3.70, logs -0.34
        [252] = 3.74, -- Unholy Death Knight: sheet 3.76, bloodmallet 3.72
        [269] = 4.92, -- Windwalker Monk: sheet 4.38, bloodmallet 4.76, logs +0.35
    },
}
